const errorCodes = {
	LIVE_ALREADY_INIT: 'LIVE_ALREADY_INIT',
	INVALID_INIT_LIVE_PARAMS: 'INVALID_INIT_LIVE_PARAMS',
	SOCKET_NO_LIVES: 'SOCKET_NO_LIVES',
	LIVE_NOT_EXISTS: 'LIVE_NOT_EXISTS'
}

exports.errorCodes = errorCodes;